FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache openssl

RUN npm i -g pnpm

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/api/package.json ./apps/api/

RUN pnpm install --frozen-lockfile --filter @checkout/api

COPY apps/api/prisma ./apps/api/prisma

CMD ["pnpm", "--filter", "@checkout/api", "exec", "prisma", "migrate", "deploy"]
